### ISSUE TITLE
aspnet core 2.0 support

### ISSUE THREAD

**Issue by mikeprince3** [thefilter/AspNetCore.Identity.Elastic#7]
Thanks for putting together this project. I am trying to convert this to run in a core 2.0 web app and wondered if you have tried yet. If I get it running cleanly, I'll submit a PR but wanted to check with you first to see if you have had any luck or if you know of any roadblocks.

**Comment by srgclr** [comment]
Hi @mikeprince3,
We will accept a PR. We haven't tried it ourselves so we don't really know how hard it will be.
Thanks and looking forward to hearing from you.

**Comment by mikeprince3** [comment]
@srgclr,
I spent the day trying to get it working and wasn't able to, unfortunately, mostly due to my nascent knowledge of 2.0. I cloned another repo that was similar to yours and did get it working. I'm pretty sure you could apply my changes to your code pretty easily. I tried to double back to your project and apply the changes but I'm spent for the day and ready for a beer. Happy Friday.

my fork:
https://github.com/mikeprince3/AspNetCore.Identity.ElasticSearch

The bulk of the changes were made to these two files:
https://github.com/fvoncina/AspNetCore.Identity.ElasticSearch/pull/1/files#diff-eac467929a4de12c32faf90fdde0093a

https://github.com/fvoncina/AspNetCore.Identity.ElasticSearch/pull/1/files#diff-25fc2bcd7351d951965885e813bcb0be

**Comment by srgclr** [comment]
Closed by PR #8
